apiVersion: v1
kind: PersistentVolume
metadata:
   name: pv-minio
spec:
   capacity:
      storage: 50Gi
   volumeMode: Filesystem
   accessModes:
   - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
   storageClassName: direct-csi-min-io
