kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-test1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: kubernetes-demo-storage-policy
  resources:
    requests:
      storage: 2Gi
